name: update and publish the scoop bucket
on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: run autoupdate
        uses: foosel/scoop-checkver-action@main
        with: bucket
      - name: auto update scoop-bucket
        run: |
          while read file; do
            if [[ $file == bucket/* ]] && [[ $file == *.json ]]; then
              version=$(cat $file | jq -r .version)
              manifest=$(basename $file .json)
              message="$manifest: Update to version $version"
              git add "$file"
              git commit -m "$message"
            fi
          done < <(git diff --name-only)
          git push
#          cd scoop/bucket
#          cp scoop/bucket scoop/bucket/old
#          cat scoop/bucket/kbcli.json | jq '.version="${{ inputs.VERSION }}"'
